# Generated by Django 5.2.3 on 2025-06-28 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_mgmt', '0002_salesperson_groups_salesperson_is_superuser_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesperson',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
